Backendless/JS-SDK

libs/backendless.d.ts
libs/backendless.js

fix: (UserService) request should always be an object (not null)
fix: type definitions for social login methods missed

fix: (UserService) social login methods & type definitions

---

libs/backendless.js

fixed a bug in isValidLogin method when use Backendless.Async and UserToken does not exist

fixed isValidLogin method

---

libs/backendless.js

- don't use the method 'catch' of Promises
- use Utils.isObject for checking of variable and also check it is not null

fix (Backendless JS SDK): old IE support

---

libs/backendless.d.ts
libs/backendless.js
tests/tsd.ts

http://bugs.backendless.com/browse/BKNDLSS-12166

BKNDLSS-12166

---

libs/backendless.js

Login With Facebook SDK: pass facebook permissions options

---

examples/data-service/index.html
examples/data-service/js/app.js
examples/file-service/index.html
examples/file-service/js/files-example.js
examples/geo-service/citysearch/js/citysearch.js
examples/user-service/index.html
examples/user-service/js/user-example.js
libs/backendless.d.ts
libs/backendless.js

- change API calls
- change handlers of API calls response
- fix examples

Remove App Version and collections methods

---

libs/backendless.js

fix parsing user after social login

---

libs/backendless.d.ts
libs/backendless.js

add utils methods
- castArray
- map
- toUri
- throwError
- addWhereClause
- move the service function to Utils
- make Utils a private module

Enrich Utils

---

libs/backendless.js

Fix Files Service API method 'exists'

Files exists fix

---

examples/file-service/css/fileService.css
examples/file-service/index.html
examples/file-service/js/files-example.js

File Service examples

---

examples/file-service/js/files-example.js
libs/backendless.js

- add handling of error of HTTP request
- fix files service example

Add HTTP request error handling

---

libs/backendless.js

fix (Users Service): remove wrapAsync from getUserRoles method

---

libs/backendless.d.ts
libs/backendless.js

Change signature from
`Backendless.Files.Permissions.grantUser( userid, url, 'READ' );`
to 
`Backendless.Files.Permissions.READ.grantUser( userid, url );`

Files Permissions: change methods signature

---

src/backendless.d.ts
src/backendless.js

fix (TS defs) uploadFile method require overwrite argument passing

Extract async handler for upload file method

---

src/backendless.d.ts
src/backendless.js

- change push-notification methods
- add internal object _DEVICE_
- add method _setupDevice_
- some code style changes

Messaging. Push notification methods changes

---

libs/backendless.d.ts
tests/tsd.ts

- fix TypeScript definition for "subscribe" method of Messaging Service

feat: (Messaging) TypeScript def

---

src/backendless.d.ts
src/backendless.js

- BKNDLSS-14852 
- BKNDLSS-14851 
- BKNDLSS-14850

Backendless.Messaging: fix bugs with overwriting of args

---

src/backendless.d.ts
test/tsd.ts

- fix TypeScript definition for "subscribe" method of Messaging Service
- fix test for TypeScript

feat: (TypeScript) TypeScript definition

---

libs/backendless.js

Do not remove user-token from User object

Remove restriction for using Backendless.Data.of('Users') notation

---

examples/data-service/relations-management/index.html
examples/data-service/todo-app/index.html
examples/file-service/index.html
examples/geo-service/citysearch/index.html
examples/messaging-service/chat/index.html
examples/user-service/index.html
package.json
src/backendless.js
test/e2e/helpers/sandbox.js
test/e2e/specs/cache.js
test/e2e/specs/persistence.js
test/e2e/specs/users.js

* Remove restriction for using Backendless.Data.of('Users') notation
* Do not remove user-token from User object
* Update console-sdk version
* Fix tests
* Fix urls to SDK in examples

Fix tests and some minor improves

---

src/backendless.d.ts
src/backendless.js
test/tsd.ts

`sendEmail` method should return Message status instead of object.

Send email response

---

src/backendless.d.ts
src/backendless.js
test/e2e/specs/persistence.js

- remove unsupported method bulkCreate
- fix method bulkDelete
- add tests for method bulkDelete

Data Service Bulk Operations Fix

---

src/backendless.js

I've added the functionality to setWhereClause on a LoadRelationsQueryBuilder, I actually stole a bunch of the functionality from the standard QueryBuilder.

WhereQuery on a LoadRelationsQueryBuilder.

---

src/backendless.js

Remove `Data.remove` response parsing

fix (persistence) remove method should return deletion time

---

src/bl/custom-services.js
src/bl/events.js
src/cache/index.js
src/commerce/index.js
src/counters/counters.js
src/data/index.js
src/data/permissions/persmission.js
src/data/store/index.js
src/decorators/deprecated.js
src/decorators/index.js
src/files/index.js
src/files/persmissions/persmission.js
src/geo/index.js
src/geo/tracker-monitor/index.js
src/index.js
src/logging/index.js
src/messaging/index.js
src/users/index.js

refactor: (Core) Decorators

---

.babelrc
package.json

- add polyfill for Object.setPrototypeOf

Build polyfill

---

backendless.d.ts
src/data/query-builder.js

Add new method to query builder - addRelated

---

backendless.d.ts
src/urls.js
src/users/index.js
src/users/login-as-guest.js
test/tsd.ts

Add guest login

---

backendless.d.ts
src/index.js

Revert Backendless.Persistence and mark it deprecated

---

backendless.d.ts
src/data/query-builder.js
src/data/store/extract-query-options.js
test/e2e/specs/data-relations.js
test/tsd.ts

- add an ability to specify "relationsPageSize" for Data.find api

---

backendless.d.ts
src/messaging/methods/push-with-template.js
test/e2e/helpers/sandbox.js
test/e2e/specs/messaging.js
test/tsd.ts

- add an ability to mock API requests for testing

- fix PushWithTemplates API

---

src/local-cache/index.js
src/local-cache/local-storage.js
test/unit/helpers/sandbox.js
test/unit/specs/local-cache/browser.js
test/unit/specs/local-cache/virtual.js

- there was a problem when the same `user-token` is used for different apps

- fix the problem with cross-apps storage

---

src/messaging/helpers/email-envelope.js
test/unit/specs/messaging/emails.js

Cast addresses in email envelope if passed string instead of array

---

backendless.d.ts
test/tsd.ts

- fix signatures for `Data.find Data.findById Data.findFirst Data.findLast` methods

- fix signatures for Data.find with query

---

backendless.d.ts
src/data/index.js
src/data/json-update-builder.js
src/data/store.js
src/index.js
test/e2e/helpers/tables.js
test/e2e/specs/data-json.js
test/tsd.ts
test/unit/specs/data/json-update-builder.js
test/unit/specs/namespace.js

upd - json support

---

backendless.d.ts
src/users/index.js
test/tsd.ts
test/unit/specs/users/emails.js

BKNDLSS-22922 - Change resendEmailConfirmation signature

BKNDLSS-22922 - Change resendEmailConfirmation signature

---

src/data/data-query-builder.js
src/data/store.js
test/unit/specs/data/find.js
test/unit/specs/data/parser.js
test/unit/specs/data/query-builder.js
test/unit/specs/data/users.js

BKNDLSS-21168 - support for DataQueryBuilder in findFirst and findLast

BKNDLSS-21168 support for DataQueryBuilder in findFirst and findLast (JS)

---

backendless.d.ts
test/tsd.ts

BKNDLSS-24135 - Method "upload" doesn't return URL

BKNDLSS-24135 - Method "upload" doesn't return URL

---

src/data/store.js
test/e2e/helpers/utils.js
test/e2e/specs/data-distinct.js
test/e2e/specs/data-group-by.js
test/e2e/specs/data-where-clause.js
test/unit/specs/data/find.js

BKNDLSS-23694 - [SUPPORT] Find data objects via POST

BKNDLSS-23694 - [SUPPORT] Find data objects via POST

---

backendless.d.ts
src/unit-of-work/op-result.js
test/tsd.ts
test/unit/specs/transactions/basic.js
test/unit/specs/transactions/op-result.js

- fix OpResult.setOpResultId method

---

src/files/index.js
test/unit/specs/files/basic.js
test/unit/specs/files/browser.js

BKNDLSS-24975 - Add upload file block for CODELESS

BKNDLSS-24975 - Add upload file block for CODELESS

---

backendless.d.ts
src/users/index.js
test/tsd.ts
test/unit/specs/users/utils/client-locale.js

Make namespace UsersUtils public

Draft: Make namespace UsersUtils public

---

backendless.d.ts
src/data/index.js
src/urls.js
test/tsd.ts
test/unit/specs/data/store.js

Add getTableNameById method

---

src/hive/stores/list.js
src/hive/stores/sorted-set.js
test/unit/specs/hive/list.js
test/unit/specs/hive/sorted-set.js

Hive. List and Sorted store methods not work

Hive. List and Sorted store methods not work

---

backendless.d.ts
test/tsd.ts

Hive. Key Value. Instance "Set" signatures

Hive. Key Value. Instance "Set" signatures

---

backendless.d.ts
src/hive/stores/list.js
test/tsd.ts
test/unit/specs/hive/list.js

Hive. ListStore. Add support JSONValue to Method "set"

Hive. ListStore. Add support JSONValue to Method "set"

---

backendless.d.ts
src/index.js
src/management/data.js
src/management/index.js
src/urls.js
test/tsd.ts
test/unit/specs/management/data.js

Add the Create Table API to JS-SDK

Add the Create Table API to JS-SDK

---

backendless.d.ts
src/automations/index.js
src/index.js
src/urls.js
test/tsd.ts
test/unit/specs/automations/basic.js

Automations API.  Add methods: activateFlowByName, activateFlowTrigger

Automations API

---

src/automations/index.js
test/unit/specs/automations/basic.js

Automations. App Logic trigger not work without req. body

Automations. App Logic trigger.

---

backendless.d.ts
src/automations/index.js
test/tsd.ts
test/unit/specs/automations/basic.js

Automations. Support executionID for activateFlowTriggerById

Automations. Support executionID for activateFlowTriggerById
